model_name: 'codellama-13b-config'
model_path: ["/data/models/code_models/codellama/CodeLlama-13b-hf/"]
type: ["CR", "CUF", "CUR"]
# type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "CodeLlama-13b-hf"
max_memory: '{1:"80GIB"}'