model_name: 'codellama-34b-config'
model_path: ["/data/models/code_models/codellama/CodeLlama-34b-hf/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "CodeLlama-34b-hf"
max_memory: '{2:"80GIB", 3:"80GIB"}'