model_path: ["/data/models/code_models/codellama/CodeLlama-34b-hf/"]
file_path: ["/data/project/dongmh/codebench/data/leetcode_C++.json", "/data/project/dongmh/codebench/data/leetcode_java.json", "/data/project/dongmh/codebench/data/leetcode_C++.json", "/data/project/dongmh/codebench/data/leetcode_java.json"]
type: ["CUF", "CUF", "CUR", "CUR"]
batch_size: 1
# output_path: "/data/project/pj/h800-4/API/rag/codebench/code_review_result.jsonl"
output_path: "/data/project/dongmh/codebench/max_length_4096_result/"
max_memory: '{2:"80GIB"}'