model_name: 'deepseek-coder-1.3b-base-config'
model_path: ["/data/models/code_models/deepseek/deepseek-coder-1.3b-base/"]
file_path: ["/data/project/dongmh/codebench/data/leetcode_C++.json", "/data/project/dongmh/codebench/data/leetcode_java.json", "/data/project/dongmh/codebench/data/leetcode_C++.json", "/data/project/dongmh/codebench/data/leetcode_java.json"]
type: ['CM']
#type: ["CUF", "CUF", "CUR", "CUR"]
batch_size: 1
# output_path: "/data/project/pj/h800-4/API/rag/codebench/code_review_result.jsonl"
output_path: "deepseek-coder-1.3b-base"
max_memory: '{2:"80GIB"}'