model_name: 'deepseek-coder-6.7b-base-config'
model_path: ["/data/models/code_models/deepseek/deepseek-coder-6.7b-base/"]
type: ["CR", "CUF", "CUR"]
# type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "deepseek-coder-6.7b-base"
max_memory: '{3:"80GIB"}'