model_name: 'deepseek-coder-33b-base-config'
model_path: ["/data/models/code_models/deepseek/deepseek-coder-33b-base/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "deepseek-coder-33b-base"
max_memory: '{0:"80GIB", 1:"80GIB"}'
# max_memory: '{i: "20GiB" for i in range(8)}'