model_name: 'deepseek-coder-1.3b-base-config'
model_path: ["/data/models/code_models/deepseek/deepseek-coder-1.3b-base/"]
type: ["CR", "CUF", "CUR"]
# type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "deepseek-coder-1.3b-base"
max_memory: '{2: "80GIB"}'
# max_memory: '{i: "20GiB" for i in range(8)}'