model_name: 'starcoder2-7b-config'
model_path: ["/data/models/code_models/starcoder/starcoder2-7b/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "starcoder2-7b"
max_memory: '{0:"80GIB"}'