model_name: 'codellama-7b-config'
model_path: ["/data/models/code_models/codellama/CodeLlama-7b-hf/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "CodeLlama-7b-hf"
max_memory: '{i: "20GiB" for i in range(8)}'