model_name: 'starcoder2-15b-config'
model_path: ["/data/models/code_models/starcoder/starcoder2-15b/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "starcoder2-15b"
max_memory: '{1:"80GIB"}'