model_name: 'starcoder2-3b-config'
model_path: ["/data/models/code_models/starcoder/starcoder2-3b/"]
type: ["CR", "CUF", "CUR"]
# type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "starcoder2-3b"
max_memory: '{4:"80GIB"}'